// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACg2M0p6rgPDBoYoQMzwiJ7vfLTNsrlRk',
    appId: '1:681491052660:web:398a42790ae6767e04f921',
    messagingSenderId: '681491052660',
    projectId: 'e-commerce-78ece',
    authDomain: 'e-commerce-78ece.firebaseapp.com',
    storageBucket: 'e-commerce-78ece.firebasestorage.app',
    measurementId: 'G-KJXNG11NBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-pmBHsUsAixTStY5yfAD-7PktqMPLRHI',
    appId: '1:681491052660:android:a4a90217f451efca04f921',
    messagingSenderId: '681491052660',
    projectId: 'e-commerce-78ece',
    storageBucket: 'e-commerce-78ece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Q7QgkGg2a9Fhr6FVMr52ZkyuNJSsZs4',
    appId: '1:681491052660:ios:f8d8e55f6228fae704f921',
    messagingSenderId: '681491052660',
    projectId: 'e-commerce-78ece',
    storageBucket: 'e-commerce-78ece.firebasestorage.app',
    iosClientId: '681491052660-dhsqvapeo4mm9bnu5p2q934rdh2jqa8q.apps.googleusercontent.com',
    iosBundleId: 'e-commerce',
  );
}
